### ISSUE TITLE
Syncing doesn't work with auxiliary .meta files

### ISSUE THREAD

**Issue by tejasvi** [OokTech/TW5-Bob#171]
Steps to reproduce:
* Create tiddler of type `text/plain`
* `.txt`, `.meta` files are generated
* `echo newtext >> textFile.txt`
* No change in client side

Currently it seems only `.tid` and `.meta` extensions are handled.
https://github.com/OokTech/TW5-Bob/blob/e40d5133445bf9858712347d77b7695d3fb6ed57/FileSystem/FileSystemMonitor.js#L90

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [ ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [ ] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by joshuafontany** [comment]
Thanks for the bug report, @tejasvi. I am currently doing a deep-read of the filesystem and syncing for BOB, but have not yet gotten to the FileSystemMonitor.js functionality. I will keep this in mind, thanks!
