### ISSUE TITLE
Moving a media file with a .meta file will not properly remove the .meta file until server restart

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#86]
Make sure you read contributing.md and check the correct boxes below and then
add your issue text here.
If you don't than the issue will be tagged as spam and closed or deleted.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [x] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`
